version: '2'
services:
    es-client-1:
    cap_add:
    - IPC_LOCK
    ulimits:
      nofile: 65536
      memlock: -1
    image: ikuturso/siemonster-alpine-es
    environment:
      ES_HEAP_SIZE: 2g
      ES_JAVA_OPTS: -Dmapper.allow_dots_in_name=true
    ports:
    - 9200:9200
    command: >
      -Des.bootstrap.mlockall=true
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.node.name="node-proteus"
      -Des.cluster.name="siemonster"
      -Des.discovery.zen.minimum_master_nodes=2
      -Des.discovery.zen.ping.unicast.hosts="es-data-node1,es-data-node2"
      -Des.index.number_of_shards=1
      -Des.index.refresh_interval=10s
      -Des.index.translog.flush_threshold=20000
      -Des.action.auto_create_index=true
      -Des.action.disable_delete_all_indices=true
      -Des.node.data=false
    hostname: proteus
    labels:
      io.rancher.scheduler.affinity:host_label: proteus=1
  es-client-2:
    cap_add:
    - IPC_LOCK
    ulimits:
      nofile: 65536
      memlock: -1
    image: ikuturso/siemonster-alpine-es
    environment:
      ES_HEAP_SIZE: 2g
      ES_JAVA_OPTS: -Dmapper.allow_dots_in_name=true
    ports:
    - 9200:9200
    command: >
      -Des.bootstrap.mlockall=true
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.node.name="node-capricorn"
      -Des.cluster.name="siemonster"
      -Des.discovery.zen.minimum_master_nodes=2
      -Des.discovery.zen.ping.unicast.hosts="es-data-node1,es-data-node2"
      -Des.index.number_of_shards=1
      -Des.index.refresh_interval=10s
      -Des.index.translog.flush_threshold=20000
      -Des.action.auto_create_index=true
      -Des.action.disable_delete_all_indices=true
      -Des.node.data=false
    hostname: capricorn
    labels:
      io.rancher.scheduler.affinity:host_label: capricorn=1
  es-data-node1:
    volumes_from:
    - es-data-node1-volume
    cap_add:
    - IPC_LOCK
    ulimits:
      nofile: 65536
      memlock: -1
    environment:
      ES_HEAP_SIZE: 4g
    image: ikuturso/siemonster-alpine-es
    command: >
      -Des.bootstrap.mlockall=true
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.node.name="node-kraken"
      -Des.cluster.name="siemonster"
      -Des.discovery.zen.minimum_master_nodes=2
      -Des.discovery.zen.ping.unicast.hosts="es-data-node1,es-data-node2"
      -Des.cluster.routing.allocation.awareness.attributes=disk_type
      -Des.node.disk_type=ssd
      -Des.node.data=true
      -Des.index.number_of_shards=3
      -Des.index.refresh_interval=10s
      -Des.index.translog.flush_threshold=20000
      -Des.action.auto_create_index=true
      -Des.action.disable_delete_all_indices=true
      -Des.threadpool.bulk.queue_size=500
    labels:
      io.rancher.scheduler.affinity:host_label: kraken=1
      io.rancher.sidekicks: es-data-node1-volume
  es-data-node1-volume:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    volumes:
    - /usr/share/elasticsearch/data
    image: alpine
    command:  /bin/ash
    labels:
      io.rancher.scheduler.affinity:host_label: kraken=1
  es-data-node2:
    volumes_from:
    - es-data-node2-volume
    cap_add:
    - IPC_LOCK
    ulimits:
      nofile: 65536
      memlock: -1
    environment:
      ES_HEAP_SIZE: 4g
    image: ikuturso/siemonster-alpine-es
    command: >
      -Des.bootstrap.mlockall=true
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.node.name="node-tiamat"
      -Des.cluster.name="siemonster"
      -Des.discovery.zen.minimum_master_nodes=2
      -Des.discovery.zen.ping.unicast.hosts="es-data-node1,es-data-node2"
      -Des.cluster.routing.allocation.awareness.attributes=disk_type
      -Des.node.disk_type=ssd
      -Des.node.data=true
      -Des.index.number_of_shards=3
      -Des.index.refresh_interval=10s
      -Des.index.translog.flush_threshold=20000
      -Des.action.auto_create_index=true
      -Des.action.disable_delete_all_indices=true
      -Des.threadpool.bulk.queue_size=500
    labels:
      io.rancher.scheduler.affinity:host_label: tiamat=1
      io.rancher.sidekicks: es-data-node2-volume
  es-data-node2-volume:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    volumes:
    - /usr/share/elasticsearch/data
    image: alpine
    command: /bin/ash
    labels:
      io.rancher.scheduler.affinity:host_label: tiamat=1
