version: '2'
services:

  '411':
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: 411-volume
      io.rancher.scheduler.affinity:host_label: capricorn=1
    tty: true
    volumes_from:
    - 411-volume
    build: https://github.com/siemonster/project-free.git#master:containers/411
    stdin_open: true
    links:
    - es-client-2:es-client
    - gmailrelay
    - alerta
    hostname: 411.${SITE_DNAME}

  411-volume:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: capricorn=1
    tty: true
    volumes:
    - /data
    build: https://github.com/siemonster/project-free.git#master:containers/411-volume
    stdin_open: true
    command: /bin/bash
