.catalog:
  version: 1
  questions:
    - variable: SITE_DNAME
      description: Specify the domain name of the site.
      label: Site domain name
      required: true
      default: projectname.portal.siemonster.com
      type: string
    - variable: BRANCH_NAME
      description: Specify the branch name to checkout.
      label: Branch name
      required: true
      default: master
      type: string

411:
  scale: 1
  retain_ip: true


